//! Build-time codegen: turns `src/vocab_enums.ron` into the Rust enums included
//! by `core::vocab`. The RON is the single source for these logic-bearing
//! vocabularies; editing it regenerates the enums (variant names are derived from
//! each `code`, PascalCase). Runs on the host for every target, so the wasm client
//! gets the same enums.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct EnumSpec {
    name: String,
    #[serde(default)]
    doc: String,
    values: Vec<EnumValue>,
}

#[derive(Deserialize)]
struct EnumValue {
    code: String,
    label: String,
}

/// snake_case / kebab-case code -> PascalCase Rust variant.
fn pascal(code: &str) -> String {
    code.split(['_', '-'])
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut chars = s.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let ron_path = Path::new(&manifest).join("src/vocab_enums.ron");
    println!("cargo:rerun-if-changed={}", ron_path.display());

    let raw = fs::read_to_string(&ron_path).expect("read src/vocab_enums.ron");
    let specs: Vec<EnumSpec> = ron::from_str(&raw).expect("parse src/vocab_enums.ron");

    let mut out = String::from("// @generated by build.rs from src/vocab_enums.ron -- do not edit.\n\n");

    for spec in &specs {
        let name = &spec.name;
        let variants: Vec<String> = spec.values.iter().map(|v| pascal(&v.code)).collect();

        if !spec.doc.is_empty() {
            let _ = writeln!(out, "/// {}", spec.doc);
        }
        let _ = writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
        let _ = writeln!(out, "pub enum {name} {{");
        for v in &variants {
            let _ = writeln!(out, "    {v},");
        }
        let _ = writeln!(out, "}}\n");

        let _ = writeln!(out, "impl {name} {{");

        let all = variants
            .iter()
            .map(|v| format!("{name}::{v}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    /// Every variant, in declaration order (feeds form dropdowns).");
        let _ = writeln!(out, "    pub const ALL: &[{name}] = &[{all}];");

        let _ = writeln!(out, "    /// The stable storage code (what lands in the DB).");
        let _ = writeln!(out, "    pub fn code(self) -> &'static str {{");
        let _ = writeln!(out, "        match self {{");
        for (v, val) in variants.iter().zip(&spec.values) {
            let _ = writeln!(out, "            {name}::{v} => {:?},", val.code);
        }
        let _ = writeln!(out, "        }}\n    }}");

        let _ = writeln!(out, "    /// The human label (what the form shows).");
        let _ = writeln!(out, "    pub fn label(self) -> &'static str {{");
        let _ = writeln!(out, "        match self {{");
        for (v, val) in variants.iter().zip(&spec.values) {
            let _ = writeln!(out, "            {name}::{v} => {:?},", val.label);
        }
        let _ = writeln!(out, "        }}\n    }}");

        let _ = writeln!(out, "    /// Parse back from a stored code.");
        let _ = writeln!(out, "    pub fn from_code(code: &str) -> Option<Self> {{");
        let _ = writeln!(out, "        match code {{");
        for (v, val) in variants.iter().zip(&spec.values) {
            let _ = writeln!(out, "            {:?} => Some({name}::{v}),", val.code);
        }
        let _ = writeln!(out, "            _ => None,\n        }}\n    }}");

        let _ = writeln!(out, "}}\n");
    }

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("vocab_enums.rs");
    fs::write(&dest, out).expect("write vocab_enums.rs");
}
